// <auto-generated />
namespace DatabaseLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cascade_userSecurity_personData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cascade_userSecurity_personData));
        
        string IMigrationMetadata.Id
        {
            get { return "201810231751494_cascade_userSecurity_personData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
